name: CI
on: [push, pull_request]
jobs:
  lint:
    name: lint the code
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: ['16']
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js v${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: npm install and test
        run: npm install-test
